{% set name = "llvm-spirv" %}
{% set version = "11.0.0" %}
{% set llvm_version = ".".join(version.split(".")[:3]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v{{ version.replace("_", "-") }}.tar.gz
  sha256: 6464a722278d37fca783cb505caf44cc8473c22fd22ff6a5d07198bc92059c4f

build:
  number: 0
  # we do not yet provide llvm on linux-s390x
  skip: true    # [s390x]

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch       # [unix]
    - m2-patch    # [win]
    - cmake
    - make        # [unix]
    - ninja       # [win]
  host:
    - llvmdev  {{ llvm_version }}
    - llvm  {{ llvm_version }}
  run_constrained:
    - llvmdev  {{ llvm_version }}

test:
  commands:
    - llvm-spirv -help

about:
  home: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
  license: NCSA
  license_file: LICENSE.TXT
  license_family: BSD
  summary: A tool and a library for bi-directional translation between SPIR-V and LLVM IR

extra:
  recipe-maintainers:
    - isuruf
