{% set name = "llvm-spirv" %}
{% set version = "10.0.0" %}
{% set llvm_version = ".".join(version.split(".")[:3]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}.2020.03.26

source:
  url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/0054933aac6614ca8a70c13ce86e4dd9de169373.tar.gz
  sha256: c3a701ec282bd2219b4c7cf5c0ffeb4a4da5053add530f90238861f957560a40

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - llvmdev  {{ llvm_version }}
    - llvm  {{ llvm_version }}
  run_constrained:
    - llvmdev  {{ llvm_version }}

test:
  commands:
    - llvm-spirv -help

about:
  home: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
  license: NCSA
  license_file: LICENSE.TXT
  license_family: BSD
  summary: A tool and a library for bi-directional translation between SPIR-V and LLVM IR

extra:
  recipe-maintainers:
    - isuruf
